language: php
php:
  - '7.1'
dist: trusty
cache:
  directories:
  - $HOME/.composer/cache/files
install:
  - composer install
  - ant
script:
  - phpunit
addons:
  code_climate:
    repo_token: 56febcaeeb8e4a22efa0e5c8dd2ea0c824cc5c9fec32ecc6f35a1154e2d892d5
after_success:
  - vendor/bin/test-reporter
  - vendor/bin/coveralls -v
  - sonar-scanner
